/**
 * Embedded Ed25519 PUBLIC key for license verification.
 *
 * ⚠️  AUTO-GENERATED by `npm run license:keygen`. Do not edit by hand.
 *
 * This is the public half of the key pair — it can ONLY verify signatures, not
 * create them, so it is safe to ship inside the POS. The matching PRIVATE key
 * lives exclusively in `license-generator/keys/private-key.pem` (gitignored)
 * and must never be distributed.
 */
export const PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAltdNq16RLzrgNRX1O4u+WZSfW2iOEOFZnQyvr5vHuSw=
-----END PUBLIC KEY-----`;
