/**
 * keygen — one-time setup for the Vendix license system.
 * ----------------------------------------------------------------------------
 * Generates a fresh Ed25519 key pair and:
 *   1. writes the PRIVATE key to license-server/keys/private-key.pem
 *      (gitignored — master signing secret; on Railway this is an ENV var)
 *   2. writes the PUBLIC key to license-server/keys/public-key.pem
 *   3. embeds the PUBLIC key into lib/licensing/public-key.ts so the POS can
 *      verify licenses without any extra wiring.
 *
 * Run from the repo root:  npm run license:keygen
 *
 * ⚠️  Re-running creates a NEW pair and INVALIDATES every license already
 *     issued with the old key. Only re-run with --force to intentionally rotate.
 */
import fs from 'fs';
import path from 'path';
import { generateKeyPair } from '../lib/licensing/core';

const keysDir = path.join(__dirname, 'keys');
const privatePath = path.join(keysDir, 'private-key.pem');
const publicPath = path.join(keysDir, 'public-key.pem');
const posPublicKeyTs = path.join(__dirname, '..', 'lib', 'licensing', 'public-key.ts');

function main() {
  if (fs.existsSync(privatePath) && process.argv[2] !== '--force') {
    console.error(
      '\n❌ A private key already exists at:\n   ' +
        privatePath +
        '\n\n   Re-running keygen would INVALIDATE all existing licenses.\n' +
        '   To intentionally rotate keys, run:  npm run license:keygen -- --force\n'
    );
    process.exit(1);
  }

  const { publicKey, privateKey } = generateKeyPair();

  fs.mkdirSync(keysDir, { recursive: true });
  fs.writeFileSync(privatePath, privateKey, { encoding: 'utf8', mode: 0o600 });
  fs.writeFileSync(publicPath, publicKey, 'utf8');

  const tsContent = `/**
 * Embedded Ed25519 PUBLIC key for license verification.
 *
 * ⚠️  AUTO-GENERATED by \`npm run license:keygen\`. Do not edit by hand.
 *
 * This is the public half of the key pair — it can ONLY verify signatures, not
 * create them, so it is safe to ship inside the POS. The matching PRIVATE key
 * lives exclusively on the license server (gitignored / env secret) and must
 * never be distributed.
 */
export const PUBLIC_KEY_PEM = \`${publicKey.trim()}\`;
`;
  fs.writeFileSync(posPublicKeyTs, tsContent, 'utf8');

  console.log('\n✅ License key pair generated.\n');
  console.log('   Private key : ' + privatePath + '   (KEEP SECRET — gitignored)');
  console.log('   Public key  : ' + publicPath);
  console.log('   Embedded in : ' + posPublicKeyTs);
  console.log('\n   For Railway: set LICENSE_PRIVATE_KEY to the contents of private-key.pem\n');
}

main();
